services:
    EzSystems\EzPlatformRedis\Cache\ItemSerializerFactory: ~
    EzSystems\EzPlatformRedis\Cache\ItemSerializerInterface:
        factory: 'EzSystems\EzPlatformRedis\Cache\ItemSerializerFactory:create'
        class: EzSystems\EzPlatformRedis\Cache\ItemSerializerInterface
        lazy: true
